version: 0.0.{build}
image: Visual Studio 2017

install:
  # MonoGame
  - ps: (new-object net.webclient).DownloadFile('http://www.monogame.net/releases/v3.5.1/MonoGameSetup.exe', 'C:\MonoGameSetup.exe')
  - ps: Invoke-Command -ScriptBlock {C:\MonoGameSetup.exe /S /v/qn}

build:
  verbosity: minimal